# Generated by Django 3.1.2 on 2020-10-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cli', models.CharField(max_length=10)),
                ('nom_cli', models.CharField(max_length=30)),
                ('ape_cli', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('fono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('cod_fam', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fam', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('desc_prod', models.CharField(max_length=50)),
                ('v_compra', models.IntegerField()),
                ('v_venta', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_prov', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_prov', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('fono_prov', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('n_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('acredito', models.BooleanField()),
                ('fec_boleta', models.DateField()),
                ('total_boleta', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('num_ped', models.AutoField(primary_key=True, serialize=False)),
                ('fec_ped', models.DateField()),
                ('desc_ped', models.CharField(max_length=50)),
                ('total_ped', models.IntegerField()),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_abono', models.DateField()),
                ('cant_abono', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.cliente')),
                ('n_bole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.venta')),
            ],
        ),
    ]
